language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install .
- pip install coverage codacy-coverage flake8 autopep8
script:
- autopep8 --aggressive --in-place --recursive .
- flake8 .
- coverage run -m unittest
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: k33k00
  password: $PYPI_PASS
  branch: master
