language: python
deploy:
  provider: pypi
  user: k33k00
  password:
    secure: oGQjWw+iWE/naw2AlfPv95c5e16I0fApGF+nqHEPYlMN7Kaz8KgJui8AHMyJGiQ/1PRGb9746u/BeVgP4lxHiqNcbeW4q0UKZCaJpA35LCIMMHe95frEzlXb9fS2EVdJ5xuVtWX7VckRg3U37JjNzBfR6pOPUkCpd8P06SZuiW1jkX49iGJsc5sPj9Dm9ctqhikPIfI5okAk9sqwmUOY0dKrQfuVqX+VNQawvUpSLzJqOi6q3su7DuZsAPJjckAkvTK4jMGqoHwgpuXjQMIXzi+PmsUQz3PIEbUykHsLTnh4hVY2gUeY0ThEv/l5hJ1hur30QJJYY0c+wFCf8LtqWT3XOPcyxgCHbhuUT2kHUP35Wssou1EkA0ZXOafxcW0iCkIWP+p0Qb3x81p511Pitv4evXZ5AOl25Xoe6jBrcSMt1xIgcz+5aIH7cDgk0zkYPgjhfryrblp+87NGnSYrWgjzv0nRNnffoZGYQxjF38+tRHzyN7zSEo38ZfOACtyHl1DXhhSfPmt7uXilCA1McUVBvIxIQLDxaFMn0VB0yEhYCGXjaF78f3ZZE3h6z2ihH8QOHhMK7aJ9OwqEH5CpHMjq9XlI8ZSZy3REMq0T28setAF34ljTtvZvGmuhkKDfPKL2Tzys7vkdOgi+gaXMfDUxz0dvIIVk+VvDtFcsiBU=
