env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install .
- pip install coverage codacy-coverage codeclimate-test-reporter
script:
- coverage run -m unittest
- coverage xml
- python-codacy-coverage -r coverage.xml
- codeclimate-test-reporter

deploy:
  provider: pypi
  user: k33k00
  password: $PYPI_PASS
  branch: master
